# Generated by Django 2.2.2 on 2019-10-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mrrs.app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_id', models.CharField(default=None, max_length=50)),
                ('client_name', models.CharField(max_length=100)),
                ('in_churn', models.BooleanField(default=0)),
                ('management_fee', models.IntegerField(blank=True, default=None, null=True)),
                ('other_revenue', models.CharField(max_length=100)),
                ('media_fees', models.FloatField(default=0)),
                ('duration', models.CharField(max_length=10)),
                ('contract', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('company_size', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('active_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('active_flag', models.BooleanField(default=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, to='app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=10)),
                ('duration_months', models.IntegerField(blank=True, default=None, null=True)),
                ('duration_years', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nps', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('active_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=20)),
                ('system_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(default=mrrs.app.models.increment_user_id, editable=False, max_length=20)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, to='app.Department')),
                ('designation', models.ForeignKey(db_column='designation_id', on_delete=django.db.models.deletion.PROTECT, to='app.Designation')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='app.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCreated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_qty', models.IntegerField(blank=True, default=1, null=True)),
                ('service_fee', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='app.Service')),
                ('service_status', models.ForeignKey(blank=True, db_column='service_status_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.System')),
            ],
        ),
        migrations.CreateModel(
            name='NpsCreated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('service', models.CharField(max_length=100)),
                ('nps', models.ForeignKey(db_column='nps_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Nps')),
            ],
        ),
        migrations.CreateModel(
            name='KpiCreated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_text', models.CharField(max_length=100, null=True)),
                ('kpi', models.ForeignKey(db_column='kpi_id', on_delete=django.db.models.deletion.CASCADE, to='app.Kpi')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('is_paid', models.BooleanField(default=0)),
                ('week_num', models.IntegerField()),
                ('client', models.ForeignKey(db_column='client_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CsmClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=None)),
                ('score', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(db_column='client_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('nps', models.ManyToManyField(to='app.NpsCreated')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCreated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_qty', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='app.Content')),
                ('content_status', models.ForeignKey(blank=True, db_column='content_status_id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.System')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='contents',
            field=models.ManyToManyField(to='app.ContentCreated'),
        ),
        migrations.AddField(
            model_name='client',
            name='created',
            field=models.ForeignKey(db_column='created_id', on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(db_column='industry_id', on_delete=django.db.models.deletion.PROTECT, to='app.Industry'),
        ),
        migrations.AddField(
            model_name='client',
            name='kpi',
            field=models.ManyToManyField(to='app.KpiCreated'),
        ),
        migrations.AddField(
            model_name='client',
            name='pm',
            field=models.ForeignKey(blank=True, db_column='pm_id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_pm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(to='app.ServiceCreated'),
        ),
        migrations.AddField(
            model_name='client',
            name='writer',
            field=models.ForeignKey(blank=True, db_column='writer_id', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_writer', to=settings.AUTH_USER_MODEL),
        ),
    ]
