# Generated by Django 2.2.2 on 2019-09-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='source',
        ),
    ]
