# Generated by Django 2.2.2 on 2019-10-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='xero_id',
        ),
        migrations.CreateModel(
            name='NpsCreated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('service', models.CharField(max_length=100)),
                ('type', models.ForeignKey(db_column='nps_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Nps')),
            ],
        ),
        migrations.AddField(
            model_name='csmclient',
            name='nps',
            field=models.ManyToManyField(to='app.NpsCreated'),
        ),
    ]
