# Generated by Django 2.2.2 on 2019-10-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191007_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nps',
            old_name='type',
            new_name='nps',
        ),
        migrations.RenameField(
            model_name='npscreated',
            old_name='type',
            new_name='nps',
        ),
    ]
