# Generated by Django 2.2.2 on 2019-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_client_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_size',
            field=models.CharField(max_length=20),
        ),
    ]
