# Generated by Django 2.2.2 on 2019-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190910_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
