# Generated by Django 2.2.2 on 2019-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190910_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecreated',
            name='service_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
