# Generated by Django 2.2.2 on 2019-09-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190910_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='xero_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
