# Generated by Django 2.2.2 on 2019-09-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190912_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpicreated',
            name='kpi_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
